databases:
  - name: Posting information about shelter cats_DB
    databaseName: posting information about shelter cats_db
    user: posting information about shelter cats
    region: singapore

services:
  - type: web
    name: posting information about shelter cats
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Posting information about shelter cats_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
